name: Build

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq build-essential
      - name: test
        run: |
          $CC --version
          gcc-9 --version
          make TEST=1 test
          make TEST=1 testc
          make TEST=1 testr
        env:
          CC: gcc
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build
        run: |
          make judge
          make libjudge
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: |
            judge
            libjudge.so
        env:
          CC: gcc
